language: node_js
node_js:
  - 12

services:
  - docker

install:
  - cd backend
  - npm install -g serverless
  - travis_retry npm install
  - cd ..

before_script:
  - echo "no tests"

script:
  - cd backend
  - serverless deploy
  - cd ..

  - docker --version
  - docker build -t fjacky/todofrontend client/

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fjacky/todofrontend